[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eyd"
description = "Dokumentasi Sphinx untuk Ejaan Bahasa Indonesia yang Disempurnakan (EYD) Edisi V."
authors = [{name = "EYD core team", email = "eyd@example.invalid"}]
requires-python = ">=3.10"
readme = "README.rst"
license = {text = "CC-BY-4.0"}
dynamic = ["version"]

[project.urls]
Documentation = "https://eyd.readthedocs.io/id/latest/"
Source = "https://github.com/eyd/eyd"
